[package]
name = "ffi_ssi"
version = "0.1.0"
edition = "2021"

[dependencies]
safer-ffi = { version = "0.0.7", features = ["proc_macros", "log", "out-refs"] }
registry_resolver = {path = "../registry_resolver"}
ssi_core = { path = "../core" }
ephemeral_resolver = {path = "../ephemeral_resolver"}
tokio = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[features]
c-headers = ["safer-ffi/headers"]