/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_FFI_SSI__
#define __RUST_FFI_SSI__

#ifdef __cplusplus
extern "C" {
#endif

typedef struct RustError {

    char * error_str;

} RustError_t;


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_uint8 {

    uint8_t * ptr;

    size_t len;

    size_t cap;

} Vec_uint8_t;


#include <stdbool.h>

bool registry_create_did (
    RustError_t * rust_error,
    Vec_uint8_t address,
    Vec_uint8_t did,
    Vec_uint8_t document);

Vec_uint8_t create_identity (
    RustError_t * rust_error,
    Vec_uint8_t did_method,
    Vec_uint8_t mnemonic_input);

void free_rust_error (
    RustError_t rust_error);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_FFI_SSI__ */
