[package]
name = "ssi_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
chrono = {workspace = true}
serde_json = {workspace = true}
sha2 = "0.10.2"
signature = { path = "../signature" }
serde = { workspace = true}
mockall = "0.11.1"
thiserror = {workspace = true}
json-ld = "0.11.0"

[dev-dependencies]
rstest = "0.15.0"
map = "0.0.0"
assert-json-diff = "2.0.2"
mockall = "0.11.1"
tokio-test = "0.4.2"
async-std = "1.12.0"
iref = "2.2.2"
static-iref = "2.0.0"
locspan = "0.7.13"

[features]
static = []