[package]
name = "ssi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
chrono = "0.4.19"
rand = "0.8.5"
serde_json = "1.0.81"
sha2 = "0.10.2"
signature = "1.5.0"

[dev-dependencies]
ed25519-zebra = "3.0.0"
rstest = "0.15.0"
multibase = "0.9.1"