[package]
name = "ssi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
chrono = "0.4.19"
serde_json = "1.0.81"
sha2 = "0.10.2"
ssi-signature = {path = "../ssi-signature"}
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rstest = "0.15.0"
map = "0.0.0"
assert-json-diff = "2.0.2"
