[package]
name = "ssi-signature"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signature = "1.5.0"
ed25519-zebra = "3.0.0"
multibase = "0.9.1"
rand = "0.8.5"