name: Rust Setup

description: Install Rust toolchain

runs:
  using: "composite"
  steps:
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install Rust Toolchain
      shell: bash
      run:
        rustup toolchain install 1.74 --profile default --component rustfmt
        --component clippy

    - name: Install Protoc and cargo-make
      shell: bash
      run: ./container/deps.sh protoc cargo-make
