[package]
name = "identity"
version = "0.1.0"
edition = "2021"

[lib]
name = "identity"
crate-type = ["cdylib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
