use std::str::FromStr;

use clap::{command, Parser, Subcommand};

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
#[command(propagate_version = true)]
struct CliArguments {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Read the JSON string file in input_file and parse it into a VerifiableCredential. Then prints the VerifiableCredential
    TestIssueCredential {
        #[arg(short, long)]
        input_file: String,
    },
    /// Read the JSON string file in input_file and parse it into a VerifiablePresentation. Then prints the VerifiablePresentation
    TestIssuePresentation {
        #[arg(short, long)]
        input_file: String,
    },
    TestEd25519Signature2020 {
        #[arg(short, long)]
        input_file: String,
        #[arg(short, long)]
        key_pair_file: String,
        #[arg(short, long)]
        comparison_file: String,
    },
}

fn main() {
    let args = CliArguments::parse();
    match args.command {
        Command::TestIssueCredential {
            input_file: input_file_path,
        } => {
            let input = std::fs::read_to_string(input_file_path).unwrap();
            let vc = ssi_core::credential::VerifiableCredential::from_str(&input).unwrap();
            println!("{}", vc);
        }
        Command::TestIssuePresentation {
            input_file: input_file_path,
        } => {
            let input = std::fs::read_to_string(input_file_path).unwrap();
            let vc = ssi_core::credential::VerifiablePresentation::from_str(&input).unwrap();
            println!("{}", vc);
        }
        Command::TestEd25519Signature2020 {
            input_file,
            key_pair_file,
            comparison_file,
        } => {
            let input = std::fs::read_to_string(input_file).unwrap();
            let kp_file = std::fs::read_to_string(key_pair_file).unwrap();
            let kp: serde_json::Value = serde_json::from_str(&kp_file).unwrap();
            let private_key = kp
                .get("privateKeyMultibase")
                .unwrap()
                .as_str()
                .unwrap()
                .to_string();
            let kp = signature::suite::ed25519_2020::Ed25519KeyPair::from_private_key(
                "test".to_string(),
                private_key,
            )
            .unwrap();
            let signer: signature::suite::ed25519_2020::Ed25519DidSigner = kp.into();
            let c = ssi_core::credential::Credential::from_str(&input).unwrap();
            let vc = c
                .try_into_verifiable_credential_for_test(
                    &signer,
                    "2023-02-24T23:36:38Z".to_string(),
                    "https://vc.example/issuers/5678#z6MkrJVnaZkeFzdQyMZu1cgjg7k1pZZ6pvBQ7XJPt4swbTQ2".to_string(),
                )
                .unwrap();

            let comparison_vc_str = std::fs::read_to_string(comparison_file).unwrap();
            let comparison_vc =
                ssi_core::credential::VerifiableCredential::from_str(&comparison_vc_str).unwrap();
            assert_eq!(vc.proof, comparison_vc.proof);
            println!("Comparison VC matches VC generated by CLI")
        }
    }
}
