[package]
name = "signature"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-zebra = "3.1.0"
multibase = "0.9.1"
tiny-bip39 = "0.8.2"
thiserror = {workspace = true}
serde = { workspace = true }
sha2 = "0.10.7"

[features]
static = []
