name: Lint & Build

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 1.64

      - name: Install Protoc (required by ::pbjson_types)
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - uses: bufbuild/buf-setup-action@v1

      - name: Build
        run: |-
          cargo build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Installing Rust Tools
        run: |-
          rustup component add rustfmt
          rustup component add clippy

      - name: Linting
        run: |-
          cargo fmt --check --all
          cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Unit Tests
        run: |-
          cargo test
