name: Lint, Build & Test

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc and cargo-make
        run: ./container/deps.sh protoc cargo-make

      - name: Installing Rust Tools
        run: |-
          rustup component add rustfmt
          rustup component add clippy

      - uses: knox-networks/github-actions-public/.github/actions/setup-protofetch@main
        with:
          cross-repo-username: "developersKnox"
          cross-repo-token: ${{ secrets.PROTOFETCH_GITHUB_TOKEN }}

      - name: Test protos
        run: (cd registry_resolver; protofetch fetch) && git diff --exit-code

      - name: Build
        run: cargo build

      - name: Linting
        run: |-
          cargo fmt --check --all
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: |-
          cargo test

      - name: Run FFI tests
        run: |
          cargo make ffi-test
