name: Lint, Build & Test

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Protoc and cargo-make
        run: ./container/deps.sh protoc cargo-make

      - name: Installing Rust Tools
        run: rustup component add rustfmt clippy

      - uses: knox-networks/github-actions-public/.github/actions/setup-protofetch@main
        with:
          cross-repo-username: "developersKnox"
          cross-repo-token: ${{ secrets.PROTOFETCH_GITHUB_TOKEN }}

      - name: Test protos
        run: (cd registry_resolver; protofetch fetch) && git diff --exit-code

      - name: Build CLI
        run: cargo build --package cli --release

      - name: Add CLI to bin
        run: sudo cp $PWD/target/release/ssi_cli /bin/ssi_cli

      - name: Install Node & NPM
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Clone & Install vc-test-suite
        run: |
          git clone https://github.com/knox-networks/vc-test-suite
          cd vc-test-suite
          npm install
      - name: Run vc-test-suite
        run: |
          cd vc-test-suite
          npm run test
